[[d1_databases]]
"binding": "my_user_db",
"database_name": "my_user_db",
"database_id": "694057fb-479a-4672-b68a-8af5eaa7a01f"

[vars]
APP_NAME = "订阅管理"
SMTP_HOST = "smtp.qiye.aliyun.com"
SMTP_PORT = "465"
SMTP_USER = "noreply@skydimo.com"
SMTP_PASS = "fbn2WqHG1CnhGfyK"
SMTP_ENCRYPTION = "ssl"
SMTP_FROM = "noreply@skydimo.com"